### ISSUE TITLE
Kinetic Kame support

### ISSUE THREAD

**Issue by sdalu** [OTL/rosruby#36]
It would be nice to have it running on the ROS Kinetic Kame version
 (and would avoid the pain to learn python :) )

**Comment by bakongo** [comment]
I was able to build on kinetic using the last change in the indigo-devel branch. I am using ruby 2.4

I then copied your sample publisher to src/rosruby, changed it to be executable, and ran it with `rosrun rosruby publisher.rb`.
The failure is now this:

```
 rosrun rosruby publisher.rb
/home/ubuntu/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- gserver (LoadError)
	from /home/ubuntu/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/ubuntu/pincair/devel/.private/rosruby/lib/ruby/vendor_ruby/ros/tcpros/server.rb:8:in `<top (required)>'
```

It seems that gserver is no longer part of ruby core, and is now a gem. (see [similar](https://github.com/aarongough/mini-smtp-server/issues/9) issue).

Do you have any suggestions on how to fix this? Is there anyplace I can specify a Gemfile?

**Comment by bakongo** [comment]
update. solved the gserver issue by copying the gserver code to the rosruby lib/ directory. Like so:

`curl -fsSL https://raw.githubusercontent.com/ruby/gserver/master/lib/gserver.rb > $HOME/<stuff>/rosruby/lib/gserver.rb`

**Comment by OTL** [comment]
hi, thank you for debugging.

rosruby does not use gem in the core system now (using only for tests or
docs).
copying might become a quick fix.
(I cannot replace it with other default ruby library, because i dont have
enough time now.)

Do you know the license of the gserver?

Another possibility is using rosdep. It seems that it supports gem(i dont
know the details).

https://github.com/ros/rosdistro/blob/master/rosdep/ruby.yaml

2017/07/21 7:11 "Daniel Wiesmann" <notifications@github.com>:

**Comment by bakongo** [comment]
Hi @OTL, the license is the ruby license: https://github.com/ruby/gserver/blob/master/LICENSE.txt 


Here is the project repo: https://github.com/ruby/gserver
